
export const portfolio = [
    {
        title: 'AIchef',
        date: 'June 23 2023',
        url: 'https://strong-cascaron-121bc7.netlify.app',
        mainTopic: 'Responsive webpage, css viewport units, etc',
        introText: "In this project, I've used viewport units, media queries and more to make the page responsive. Get ready to revolutionize your cooking experience. Our website combines the power of artificial intelligence with a vast database of ingredients to help you create delicious meals effortlessly. Simply input the ingredients you have on hand, and our AI algorithm will generate personalized recipes tailored to your preferences and dietary needs",
        explanation: "Within this project, the main focus was on making the website responsive, and the form properly formatted. For the title tags on the left panel, I've used the viewport width as font size. Meaning the bigger the vw, the bigger the font. From the app first perspective, first the format is showed in a column having the two panels above each other. Then with the media query for bigger screen, body's display is set to flex, meaning a row is created. Daarnaast wordt flexbox gebruikt voor het opbouwen van de twee divs's inner-content. De divs bestaan uit de intro en main-content. Opvallend is nog dat de fonts worden vergroot wanneer de viewport groter wordt en de media querie wordt ingezet   ",  
        difficulty: '⭐️⭐️', 
        image: 'images/ai.png',     
    },
    {
        title: 'Iceshop',
        date: 'June 23 2023',
        url: 'https://gleeful-faloodeh-852c66.netlify.app/',
        mainTopic: '.forEach(), data attributes, conditionally render styles',
        introText: 'Iceshop is a restaurant ordering app, that user can use to order icecream. Only the left side the menu is showed, through the use of a list of objects. On the right side the definitve order is showed.',
        explanation: "We learned how to loop over several items in an array with for each, nameArray.forEach(function(arrayItems){}. We also worked with the filter function. We show a menu list and a order list, both in different lists with objects. To show these objects I loop through the list with .forEach. Then with loading the items on the order list, we use a button with data-type, for example data type buy. Within the data we can put the order name or id. Then we listen for clicks on the button and run the buy function with the id. Within this function we filter for this id and add this to the order list object. Then we loop over the list called order.",
        difficulty: '⭐️⭐️⭐️', 
        image: 'images/ice2.jpg',     
    },
    {
        title: 'Padel',
        date: 'June 22 2023',
        url: 'https://magical-brioche-9865f4.netlify.app/',
        mainTopic: 'Responsive webpage, css viewport units, etc',
        introText: 'Paddle sport is a website for real paddle supporters. Its a website to learn more about this amazing sport, check information about the materials necessary to play paddle, or book one of the courts.',
        explanation: 'This assignment mainly focused on responsiveness. So with starting with the mobile first take, you should focus on the small screen first and add media queries for larger screens. We learned about break points, font size (rem), padding and margin (em), and the sizes of containers/screen (%). A good thing is to always add max width for containers including images or text',   
        difficulty: '⭐️⭐️️', 
        image: 'images/padel.png',     
    },
    {
        title: 'Twimba',
        date: 'June 14 2023',
        url: 'https://peppy-paletas-5b0241.netlify.app/',
        mainTopic: '.forEach(), data attributes, conditionally render styles',
        introText: 'Twimba is a twitter clone, that users can use to tweet, follow people, and accept follow request. Futhermore, the user can retweet, like, and see responses. ',
        explanation: "We learned how to loop over several items in an array with for each, nameArray.forEach(function(arrayItems){}. We learned how to structure our program, by having a function called getXHtml, which would be rendered in a different function called rendered, which would used the getHtml function. We learned how to implement font awesome. |We learned how to use data attributes, which is extra data you can add to a HTML element. This data attribate has a key with a value. You can retrieve the value in javascript by using an event listener and then targeting the event's dataset property. Important to nate both the name of the data-set and the value are important. Zo kan je dus extra informatie meesturen, wanneer iemand op een button, link of icon klikt dat is gelinkt is aan een user, of images, etc. ",
        difficulty: '⭐️⭐️⭐️⭐️',    
        image: 'images/twimba.png',     
    },
    {
        title: 'Memegenerator',
        date: 'June 09 2023',
        url: 'https://magical-peony-851b38.netlify.app',
        mainTopic: 'Essential Javascript concepts',
        introText: "Pumpkin's perfect.. Meme picker is something everyone needs in their life. Right there available for them any time the day. Or send it to your friends and lighten up their day! ",
        explanation: 'In this project we used several different javascript concepts, such as includes(), e.target, checkbox, filter etc. Filter is used to get the correct meme linked to the users emotion. Furthermore, we used a ratio input for the different emotions', 
        difficulty: '⭐️⭐️️',  
        image: 'images/meme.png',     
    },
     {
        title: 'Quack',
        date: 'May 28 2023',
        url: 'https://stirring-creponne-4d4b20.netlify.app/',
        mainTopic: 'Javascripts essentials',
        introText: "Introducing DuckyDuck: Your Go-To App for Sending Coworker Endorsements! Say goodbye to the hassle of writing lengthy emails or struggling to find the right words to appreciate your coworkers. With DuckyDuck, a seamless endorsement-sending app, you can effortlessly express your gratitude and recognition in just a few taps. Whether its a shout-out for a job well done or a heartfelt thank you, DuckyDuck makes it easy to show your appreciation to your colleagues. Enhance your workplace relationships and create a positive, supportive environment with DuckyDuck – the ultimate tool for sending endorsements to your amazing coworkers!",
        explanation: "We've same basic javascript concepts, changing innerHTML, removing an item when clicked from database, Using firbase, Flexbox, etc. Firebase is a database that stores string values realtime. We can access these values in realtime using firebase's onValue. ",  
        difficulty: '⭐️⭐️⭐️',   
        image: 'images/ducky.png',     
    }
]

